apiVersion: apps/v1
kind: Deployment
metadata:
  name: solr
  labels:
    app: solr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solr
  template:
    metadata:
      labels:
        app: solr
    spec:
      containers:
      - name: solr
        image: bitnami/solr:7.4.0-debian-9-r55
        ports:
        - containerPort: 8983
---
apiVersion: v1
kind: Service
metadata:
  name: solr-lb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  externalTrafficPolicy: Local
  selector:
    app: solr
  ports:
    - port: 8983
      targetPort: 8983
  type: LoadBalancer