apiVersion: apps/v1
kind: Deployment
metadata:
  name: crypto-nginx-deployment
  namespace: vulnerables
  labels:
    app: crypto-nginx
    Owner: Scotty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crypto-nginx
  template:
    metadata:
      labels:
        app: crypto-nginx
        Owner: Scotty
    spec:
      containers:
      - name: crypto-nginx
        image: scotty2hotty/crypto_nginx:latest
        resources:
          limits:
            memory: "64Mi"
            cpu: "125m"