apiVersion: apps/v1
kind: Deployment
metadata:
  name: dvwa-deployment
  namespace: vulnerables
  labels:
    app: dvwa
    Owner: Scotty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dvwa
  template:
    metadata:
      labels:
        app: dvwa
        Owner: Scotty
    spec:
      serviceAccountName: svc-acc-cluster-admin-bad
      containers:
      - name: dvwa
        image: scotty2hotty/dvwa:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: dvwa-svc
  labels:
    Owner: Scotty
  namespace: vulnerables
spec:
  selector:
    app: dvwa
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
